---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
   name: inspec
   sudo: true
   sudo_options: "-u oracle"

platforms:
  - name: centos-6.9
  #- name: centos-7.3
    driver:
      network:
        - ["private_network", {ip: "192.168.33.8"}]

suites:
  - name: default
    driver:
        vm_hostname: chefd.local.com
    run_list:
      - recipe[oracle::default]
    verifier:
       inspec_tests:
          - test/smoke/default
    attributes:
